version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword!123  # Defina uma senha forte
    ports:
      - "1433:1433"
    networks:
      - spring-network
    volumes:
      - sqlserver-data:/var/opt/mssql

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://192.168.1.5:1433;databaseName=todolist;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=esther
      - SPRING_DATASOURCE_PASSWORD=avatim123
    depends_on:
      - sqlserver
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

volumes:
  sqlserver-data:
    driver: local
